language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install --upgrade setuptools
  - pip install web.py
# command to run tests
script: python -m doctest endpointSim.py
